config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments, only: [:edit, :update, :destroy]
  resources :votes, only: [:destroy]

  resources :questions, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :answers, only: [:create, :edit, :update, :destroy]
    resources :comments, only: [:create]
    resources :votes, only: [:create]
  end

  resources :answers do
    resources :comments, only: [:create]
    resources :votes, only: [:create]
  end

  root 'questions#index'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  validates :commentable_id, :content, :user, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    # @comment = @movie.comments.create(:text => "This is a comment")
    @commentable = find_commentable
    @comment = @commentable.comments.build comment_params
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment Posted.' }
        format.js
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params["id"])
    redirect_to root_path unless @comment.user_id == current_user.id
    if @comment.commentable_type == "Question"
      @question = Question.find(@comment.commentable_id)
    else
      @question = Answer.find(@comment.commentable_id).question
    end
    @comment.destroy
    redirect_to question_path(@question)
  end

  def edit
    @comment = Comment.find(params["id"])
  end

  def update
    @comment.content = params[:content]
    redirect_to root_path unless @comment.user_id == current_user.id

    if @comment.save
      redirect_to question_path(@question)
    else
      flash[:error] = "Error!"
      render 'edit'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :answer_id, :question_id)
  end

  def find_commentable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end

end

app/views/comments/_comment.html.erb
<div class="comment">
  <%= comment.user.name %> - "<%= comment.content %>"
  &nbsp;
  <% if comment.user == current_user %>
    <%= link_to "Edit Comment", edit_comment_path(comment) %>
    &nbsp;|&nbsp;
    <%= link_to "Delete Comment", [comment], method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<div class="new-comment-form">
  <%= form_for [commentable, @comment], remote: true do |f| %>
    <%= f.label :content %>&nbsp;<%= f.text_field :content, placeholder: "Your Comment" %>&nbsp;<%= f.submit 'Submit Comment' %>
  <% end %>
</div>

app/views/comments/create.js.erb
$("#<%= escape_javascript(@comment.commentable_type.downcase) %>-comment-box").append("<%= escape_javascript(render @comment) %>");
$("#pulldown-<%= escape_javascript(@comment.commentable_type.downcase) %>-comments-form").click();

app/views/comments/edit.html.erb
<div class="edit-form">
  <h4>Edit Your Comment</h4>
  <div class="error"><%= flash[:error] if flash[:error] %></div>
  <br /><br />
  <%= form_for @comment do |f| %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <%= f.submit 'Submit', class: "btn btn-primary btn-sm" %>
  <% end %>
</div>