config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments, only: [:edit, :update, :destroy]
  resources :votes, only: [:destroy]

  resources :questions, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :answers, only: [:create, :edit, :update, :destroy]
    resources :comments, only: [:create]
    resources :votes, only: [:create]
  end

  resources :answers do
    resources :comments, only: [:create]
    resources :votes, only: [:create]
  end

  root 'questions#index'
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :votes, as: :voteable, dependent: :destroy
  validates :content, :question, :user, presence: true
  validates :user_id, uniqueness: { scope: :question_id }

  def sort_by_votes
    # select('posts.*, count(votes.id) as vote_count').joins('LEFT OUTER JOIN votes on votes.answer_id = posts.id').group_by('posts.id').order('votes_count desc')
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create answer_params
    @comment =  Comment.new
    @answer.user = current_user
    @vote = Vote.new
    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer Posted.' }
        format.js
        format.json { render json: @answer, status: :created, location: @answer }
      else
        # format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @question = Question.find(@answer.question_id)
    if @answer.user == current_user
      if @answer.comments
        @answer.comments.destroy_all
      end
      @answer.destroy
      redirect_to question_path(@question)
    end
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def update
    @answer = Answer.find(params[:id])
    @answer.content = answer_params[:content]
    if @answer.save
      redirect_to question_path(@answer.question)
    else
      redirect_to edit_question_answer_path(@answer)
      flash[:error] = "Error!"
    end
  end

  def answer_params
    params.require(:answer).permit(:content, :question_id, :user_id)
  end
end

app/views/answers/_answer.html.erb
<div class="answer-container">
  <div class="answer-vote-area">
    <% if is_logged_in %>
      <div class="answer-vote-button-<%= answer.id %>">
        <% if has_voted_on(answer) %>
          <%= render partial: 'votes/cancelvote', locals: {vote: get_vote(answer)} %>
        <% else %>
          <%= render partial: 'votes/upvote', locals: {voteable: answer} %>
        <% end %>
      </div>
    <% end %>
    <div class="answer-votes-<%= answer.id %>"><%= answer.votes.count %></div>
  </div>

  <div class="answer">
    <div class="answer-content"><%= answer.user.name %> answered, <%= answer.content %>
      <span class="author-action">
        <% if answer.user == current_user %>
          &nbsp;<%= link_to "Edit Answer", [:edit, @question, answer] %>
          |&nbsp;<%= link_to "Delete Answer", question_answer_path(@question, answer), data: {confirm: "Are you sure?", :method => :delete} %>
        <% end %>
      </span>
    </div>
  </div>
</div>

<div id="answer-comment-box">
  <% if answer.comments.any? %>
    <% answer.comments.all.each do |comment| %>
      <%= render partial: 'comments/comment', locals: {comment: comment, commentable: answer} %>
    <% end %>
  <% end %>
</div>

<% if is_logged_in %>
  <div id="answer-comment-form">
    <%= render partial: 'comments/form', locals: {commentable: answer} %>
  </div>

  <div id="pulldown-answer-comments-form">
    <span class="pulldown-left">▼</span>Add a Comment<span class="pulldown-right">▼</span>
  </div>
<% end %>

app/views/answers/_form.html.erb
<div id="new-answer-form">
  <h4 class="first-heading">Post an Answer</h4>
  <%= form_for [@question, @answer], remote: true do |f| %>
    <%= f.label :content %>
    <br />
    <%= f.text_field :content, placeholder: "Your Answer" %>
    <br /><br />
    <%= f.submit 'Submit Answer' %>
  <% end %>
</div>

app/views/answers/create.js.erb
$("body").append("<%= escape_javascript(render @answer) %>");
$("#new-answer-form").hide();

app/views/answers/edit.html.erb
<div class="edit-form">
  <h1>Update Your Answer</h1>
  <div class="error"><%= flash[:error] if flash[:error] %></div>
  <%= form_for [@question, @answer] do |f| %>
    <%= f.label :content %>
    <br />
    <%= f.text_field :content %>
    <br />
    <%= f.submit %>
  <% end %>
</div>