config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments, only: [:edit, :update, :destroy]
  resources :votes, only: [:destroy]

  resources :questions, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :answers, only: [:create, :edit, :update, :destroy]
    resources :comments, only: [:create]
    resources :votes, only: [:create]
  end

  resources :answers do
    resources :comments, only: [:create]
    resources :votes, only: [:create]
  end

  root 'questions#index'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Knoverflow2016</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="navigation">
      <div id='home-button'><%= link_to "knoverflow", root_path %></div>
      <% if session[:user_id] %>
        <div id="user-links">
          Hello <%= User.find(session[:user_id]).name %>!</a>
          &nbsp;&nbsp;<span class="pipe">|<span>&nbsp;&nbsp;
          <%= link_to "Ask a Question", new_question_path %>
          &nbsp;&nbsp;<span class="pipe">|<span>&nbsp;&nbsp;
          <%= link_to "Modify Account", edit_user_path(current_user) %>
          &nbsp;&nbsp;<span class="pipe">|<span>&nbsp;&nbsp;
          <%= link_to "Log Out", session_path(current_user), {method: :delete} %>
        </div>
      <% else %>
        <div id="user-links">
          <%= link_to "sign up", new_user_path %>
          &nbsp;&nbsp;<span class="pipe">|</span>&nbsp;&nbsp;
          <%= link_to "sign in", new_session_path %>
        </div>
      <% end %>
  </div>

  <%= yield %>

</body>
</html>